
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: yongkun gui
email: anfernee.gui@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software developer in Google. Ex-VMwarer. Kubernetes, CNCF, Cloud Foundry, Cloud Native App.
  Everything in this blog only represents myself.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://anfernee.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: anferneee
github_username:  anfernee
facebook_username: yongkun.gui

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

minima:
  skin: solarized